[parity]
chain = "ropsten"
base_path = "/data/ethereum"
db_path = "/data/ethereum/chains"
keys_path = "/data/ethereum/keys"

[dapps]
path = "/data/ethereum/dapps"

[rpc]
disable = false
port = 8545
apis = ["all"]
cors = ["*"]
hosts = ["all"]
interface = "all"

[websockets]
disable = false
port = 8546
interface = "all"
origins = ["all"]
apis = ["all"]
hosts = ["all"]

[ipc]
disable = true
