kind: Service
apiVersion: v1
metadata:
  name: chainlink-svc
spec:
  selector:
    app: chainlink
  ports:
    - name: cl
      protocol: TCP
      port: 6688
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chainlink-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chainlink-deploy
spec:
  selector:
    matchLabels:
      app: chainlink
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chainlink
    spec:
      containers:
        - name: chainlink
          image: smartcontract/chainlink
          args: ["node", "--password", "twochains"]
          ports:
            - containerPort: 6688
          env:
            - name: ROOT
              value: "/data/chainlink"
            - name: LOG_LEVEL
              value: "debug"
            - name: ETH_URL
              value: "ws://ethereum-svc.default.svc.cluster.local:8546"
            - name: ETH_CHAIN_ID
              value: "3"
          volumeMounts:
            - name: chainlink-storage
              mountPath: /data
      volumes:
        - name: chainlink-storage
          persistentVolumeClaim:
            claimName: chainlink-pv-claim
---
kind: Service
apiVersion: v1
metadata:
  name: ethereum-svc
spec:
  selector:
    app: ethereum
  ports:
    - name: rpc
      protocol: TCP
      port: 8545
    - name: ws
      protocol: TCP
      port: 8546
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ethereum-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ethereum-deploy
spec:
  selector:
    matchLabels:
      app: ethereum
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ethereum
    spec:
      containers:
        - name: ethereum
          image: smartcontract/ethereum
          args: ["--config", "/devnet/k8s/ropsten.toml"]
          ports:
            - containerPort: 8545
            - containerPort: 8546
          volumeMounts:
            - name: ethereum-storage
              mountPath: /data
      volumes:
        - name: ethereum-storage
          persistentVolumeClaim:
            claimName: ethereum-pv-claim
